[theme]
base = "light"
primaryColor = "#B4513D"
backgroundColor = "#EFE8D8"
secondaryBackgroundColor = "#ECE3D0"
textColor = "#2B251D"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
